### ISSUE TITLE
3.4.5 found a bug

### ISSUE THREAD

**Issue by Tantalus-X** [sigmasin/OriDERandomizer#42]
A see me self Oo and the music is also gone at this point cane you fix thes bug 
![Ori DE 3 4 5 bug](https://user-images.githubusercontent.com/31192532/81052067-1d538080-8ec3-11ea-9289-fe838e438375.png)

**Comment by sparkle-preference** [comment]
these issues are a side effect of some changes that we made to stop the randomizer from softlocking after the finishing the ginso escape. 
unfortunately, I have no idea how we would go about fixing them.
